### ISSUE TITLE
PROPOSAL: Deprecate current iteration of Auto Mod and re-implement in Go

### ISSUE THREAD

**Issue by jpmcb** [jpmcb/OSU-Auto-Mod#23]
Related to PR #22 

In my opinion, the ability to accurately test the Node JS server / client framework is innately challenging and the current implementation's method for testing new features has become unmaintainable. 

Other paradigms, such as Golang, would make this much easier and offer native solutions for unit testing, pipeline integration, client/server testing, proxy server testing, and BDD. 

I propose the following:

* Auto Mod is re-written in Golang optimized for lite weight deployment.
* A full suite of tests are implemented for the current set of features
* Tests are required for all new features and PRs
* A development / contributing Docker Image is created to enable other collaborators to easily start helping.

----
## Discussion:
What are the merits of continuing to maintain this code base in Node? What are the pros and cons offered by testing libraries in Node and Go? What could be optimized by moving to Go?

**Comment by Jedeu** [comment]
Given the scale of this project, I think that the choice is dependent on who would be maintaining the project most and their strengths. There a couple of questions that could help us out:

1. Are we more comfortable writing in Go than in JS? 
2. How many features have we rolled out  that would require a re-write if we did it in Go?
3. What resources are available (documentation, tutorials, etc.) for each language?
4. How would Go facilitate with the deployment compared to JS?

I believe that the tools needed to test are available for both Go and JS; the former actually suggests you don't need to use a tool in most cases and can build out test cases using Go's std lib alone, while the latter has simple things like Ava, and Sinon.js for making stubs.

I'm also cool with Dockerizing this service as well to make things easier for deployment's sake.

**Comment by jpmcb** [comment]
Great questions @Jedeu, and yes, I think it is largely dependent on who would be the main maintainer of this could base. For the most part, it has primarily been me and @hschallh maintaining this project.

1. I am very comfortable in Go from my professional work
2. This would require a full, complete re-write of the bot.
3. There may be more support for writing slack bots in JS directly from Slack, but a quick google search reveals that there are plenty of available tutorials and open source code bases in Go to view. Further, the overall documentation and support for Go 1.12 is very thorough.
4. I believe this gets at the core issue: Node offers no built in, pre-packaged testing library. Go offers the `go test ... ` built in tool. Go also offers a built in proxy server testing framework through `ghttp`. The problem that I have experienced with testing and building projects in Node is there is no centralized, standard way to test code. This leads to the vast number of testing frameworks and packages making it challenging to accurately test the various server / client behaviors. With Go, we would be able to easily implement this as we develop it from the ground up.

**Comment by Jedeu** [comment]
@jpmcb Those are some good points and I agree that Go is overall a nicer language to work with. I'd totally be down to do a re-write in Go and it seems like the impact of taking the time to re-write is small given that there aren't too many users (?) of the bot at the moment. Let me know where I could help out! I have some experience with making docker images and Go thanks to my work as well 😄
